# This file allows testing your addon using travis CI servers to use it you'll need to
# create an account in travis.org and enable your addon there. #
# By default it will test linux 64bit and osx against the master and stable OF branches. 
# Other platforms can be enabled by uncommenting the corresponding sections.
#
# If any extra install is needed to use the addon it can be included in the corresponding
# install script in:
#
# scripts/ci/$TARGET/install.sh
#

env:
  global:
    - APPNAME="NatNetOSCrecorder"
    - secure: "u8AmjOK5shYxMIL03aA/sLmTOfV+Xkq2YugLpbQGW6NbejIqdvY4f86uPfbR0hN7y/LZAQc9O11BES+z12+0mCBP/aX0CZBUC2VTUivCsSV3W5LJ5SUbmRNjNMtasRCm29VRdC/FDmJcAPdFa5c6g3WccfzTZMVL7tHiQBqDkxupCEwKaNBqcPiErbCFSZG6bH/0cXiMH3e+H363zujjYX5/U43lhzDbga5zao+c29aU3IEd95vJDtoP2nYXduCOqVlVZmr8AkL8ihyO990/Ib6yXB0roR3+IElElD4SvXQlxXy2Ual3GA0/J//AcP29xp7F1vptJcaAijtgLRRyaq2sytQrhDaHX1kKFZc3slmr6xJYdbCfaV5PmBdc3cXXB0XvJNpoV2S5CYspSVLLRVleL0WbutNQawR2oc7TurTdG5oely4V8lI3PEUWAaildiZuhbasBu3ukbS/8GHeJe3OjgkmT+XvKDSms6sigOuvVBOwgbTbSasF5OFr6zQaywHGA+SmKKk1xcc2Ta/ao6/G3U3oZwc8GqLzJrptf4Tpx72l8QSoZq4uF7OnGgnq3uAvrx+peZi9o2uFxZwRCpq6JDJScwxSOWsWWIxSOwTCmF8bm/KMcW7getXvjRDunx9m3ifWJyPqZHTWLC2RTgDapNbSRVSsLky87+XM+vQ="
language: c++
compiler: gcc
sudo: true
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

# Linux 64bit, OF master
  - os: linux
    dist: xenial
    sudo: required
    env: TARGET="linux64" OF_BRANCH="master"
    addons:
      ssh_known_hosts: pong.hku.nl
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - sshpass
          - libssl-dev
          - openssl
#          - gdb

# Linux 64bit, OF stable
  - os: linux
    dist: xenial
    sudo: required
    env: TARGET="linux64" OF_BRANCH="stable"
    addons:
      ssh_known_hosts: pong.hku.nl
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - sshpass
          - libssl-dev
          - openssl

# OSX, OF master
  - os: osx
    osx_image: xcode9.2
    compiler: clang
    env: TARGET="osx" OF_BRANCH="stable" MACOSX_DEPLOYMENT_TARGET=10.9
    addons:
      ssh_known_hosts: pong.hku.nl

# OSX, OF stable:  Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="osx" OF_BRANCH="stable"

# Linux ARM6, OF master: Uncomment following lines to enable 
#  - os: linux
#    sudo: required
#    dist: trusty
#    env: TARGET="linuxarmv6l" OF_BRANCH="master"


# Linux ARM6, OF stable:  Not supported yet
#  - os: linux
#    sudo: required
#    dist: trusty
#    env: TARGET="linuxarmv6l" OF_BRANCH="stable"

# Linux ARM7, OF master: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="linuxarmv7l" OF_BRANCH="master"
#    cache:
#      directories:
#        - ~/rpi2_toolchain
#        - ~/firmware-master
#        - ~/archlinux

# Linux ARM7, OF stable:  Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="linuxarmv7l" OF_BRANCH="stable"
#    cache:
#      directories:
#        - ~/rpi2_toolchain
#        - ~/firmware-master
#        - ~/archlinux


# Emscripten, OF master: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="emscripten" OF_BRANCH="master"
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#        packages:
#          - libstdc++6


# Emscripten, OF stable: Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="emscripten" OF_BRANCH="stable"
#    addons:
#      apt:
#        sources:
#          - ubuntu-toolchain-r-test
#        packages:
#          - libstdc++6


# iOS, OF master: Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="ios" OF_BRANCH="master"


# iOS, OF stable: Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="ios" OF_BRANCH="stable"


# tvOS, OF master: Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="tvos" OF_BRANCH="master"


# tvOS, OF stable: Not supported yet
#  - os: osx
#    osx_image: xcode8
#    compiler: clang
#    env: TARGET="tvos" OF_BRANCH="stable"


# Android armv7, OF master: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="armv7" OF_BRANCH="master"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


# Android armv7, OF stable: Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="armv7" OF_BRANCH="stable"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


# Android x86, OF master: Uncomment following lines to enable 
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="x86" OF_BRANCH="master"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


# Android x86, OF stable: Not supported yet
#  - os: linux
#    sudo: false
#    env: TARGET="android" OPT="x86" OF_BRANCH="stable"
#    cache:
#      directories:
#        - ~/android-ndk-r12b


  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc

install:
  - git submodule update --init --recursive
  - cd ~
  - git clone --depth=1 --branch=$OF_BRANCH https://github.com/openframeworks/openFrameworks
  - cd openFrameworks
# fails so we do it ourselves - scripts/ci/$TRAVIS_OS_NAME/install.sh
  - if [ "$TARGET" == "linux64" ]; then 
      sudo scripts/linux/ubuntu/install_dependencies.sh -y;
      if [ -f scripts/linux/download_libs.sh ]; then 
        scripts/linux/download_libs.sh;
      fi
    elif [ "$TARGET" == "osx" ]; then
      brew update;
      brew upgrade coreutils;
      brew install https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb;
      if [ -f scripts/$TARGET/download_libs.sh ]; then 
        scripts/$TARGET/download_libs.sh;
      fi
    fi
#  - scripts/linux/compileOF.sh
  - if [ "$TARGET" == "linux64" ]; then
      cd libs/openFrameworksCompiled/project;
      make Debug;
    fi
  - cd ~/openFrameworks/addons
  - git clone --depth=1 https://github.com/jvcleave/ofxImGui.git

script:
#  - scripts/ci/addons/build.sh
  - cd $TRAVIS_BUILD_DIR/..
  - mv $APPNAME ~/openFrameworks/apps/devApps/
  - cd ~/openFrameworks/apps/devApps/$APPNAME
  - make Debug
  - cd ..
  - mv $APPNAME $TRAVIS_BUILD_DIR 
  - cd $TRAVIS_BUILD_DIR;

git:
  depth: 256

after_success:
  - git checkout config.make
  - git fetch --all --tags
  - cd bin
# TRAVIS_TAG is ony set when it is a tag (or release)
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then 
      if [ -n "$TRAVIS_TAG" ] || [[ $TRAVIS_BRANCH == "master" ]]; then
        zip -r $( echo $TRAVIS_REPO_SLUG | cut -d"/" -f2)_${TRAVIS_OS_NAME}_$( git describe --tag --always --dirty --abbrev=4).zip *;
      else
        zip -r $( echo $TRAVIS_REPO_SLUG | cut -d"/" -f2)_${TRAVIS_OS_NAME}_${TRAVIS_BRANCH}_$( git describe --tag --always --dirty --abbrev=4).zip *;
      fi

    fi
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then export SSHPASS=$BBPWD; fi
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then sshpass -e scp *.zip buildbot@pong.hku.nl:public_html/nightly/; fi
  - cd ..

deploy:
  provider: releases
  api_key:
    secure: Pc4nH4Lrdxqb7vC2yjvErH3ByFc9EbpQB1cEGUNFWSZnSJJ9okg2f3bIJYT+swapcdFZ2yliQzhoSVznt8yuPdR0L+A+olFCngkBs3XQf3V36cXFI6YVa5/PYW5+qXYEoh+f9zwYEvYrx5famVHFP5wwPj6X2hNe3XsyzIjLwixL0L6ASIZ4gS991DdQKLMPFa4qYbdHxmJZPEGGXRogunndBgbyEwfEsHeSaPDNORapHBI34vlIyouCnU7lgeyNAyX0K7qwa0FO1G06WB0WMWZb33rTh043CUNAGtZQDWZftQOAG3tu0nutewx3G7VE5iTF3VP+av4Y/ikCXXag+DjxzsPn54UE1IaiNa+FT8+eBfLRTG8d1G298VJeSr+7aP13F6FCwNsMeRzM3Vv2g1gsWfOrn0In9yP3h9vQmaqcl/2i4e4/6VkyRJnlddj5+l82dO3hbucf1EftcaHeu7ghlfTkQviQ0tkkfN1V2u4ox+nBuiXspWeltOqlFAlZE+BOyrxX232RC6qWCgQlEkCf+PxT9Aaj+7bm0iedaS+29usYLgBfjb3oGWyFd465rBzKC5FsJ40CQtGqZeOjZRxsqBlCPj8Q6Ems3wYJB8fZz2afEYquLwwyWNU0R4whBvYbpPeE3mNH4IraDvNnZ79YV1ecuxwOW7Tdjw+knyM=
  file_glob: true
  file: bin/*.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: hku-ect/NatNetOSCrecorder
